### ISSUE TITLE
Manual overriding of slug

### ISSUE THREAD

**Issue by ZeldOcarina** [YuriGor/mongoose-slug-updater#16]
Hello Yuri!

I am trying to setup a field to enable overriding of slug but can't quite find a hook to do so.

Mongoose `findOneAndUpdate({ slug })`  doesn't work as probably the plugin runs after Mongoose did its job.

I've searched through the documentation but could not find this feature.

I am handling by manually changing slugs on Atlas but it's definitely not an optimal setup.

Is it possible to achieve this in any other way?

Thanks! :)

**Comment by YuriGor** [comment]
Hi, you probably want this
https://github.com/YuriGor/mongoose-slug-updater/blob/master/README.md#updating-slug-or-keeping-it-permanent
It's possible to configure plugin which exactly events should it track.

**Comment by ZeldOcarina** [comment]
Yes this handles sorry I could not find it! 😅
