### ISSUE TITLE
Duplicate slug generated when subdocument added to existing document

### ISSUE THREAD

**Issue by mykwillis** [YuriGor/mongoose-slug-updater#25]
I have a document that has an array of subdocuments. Each subdocument contains a permanent slug unique to the parent:

```
const ChildSchema = mongoose.Schema({
  title: {
    type: String
  },
  slug: {
    type: String,
    slug: 'title',
    index: true,
    permanent: true,
    slugPaddingSize: 4,
    uniqueGroupSlug: '/_id',
  },
});

const ParentSchema = mongoose.Schema({
  children: [ChildSchema],
});

const ExampleModel = mongoose.model('ParentSchema', ParentSchema);
```

If I create an initial document with some children:

```
    const doc = await ExampleModel.create({
      children: [
        {
          title: 'This is nested subtitle',
        },
        {
          title: 'This is nested subtitle',
        },
      ],
    });

```
then everything is fine; both of the new subdocuments get properly generated and unique slugs.

However, if I update the document with another child subdocument:

```
    doc.children.push(
    {
      title: 'This is nested subtitle',
    });
    await doc.save()

```

then the new document receives a duplicate slug.

**Comment by YuriGor** [comment]
Thank you for report and PR! 
Sorry for late reaction, something went wrong with notifications about this project.
