### ISSUE TITLE
Update with $set on array fields throw conflict

### ISSUE THREAD

**Issue by vilipwong** [YuriGor/mongoose-slug-updater#7]
I have collection Products with schema : 
```
name: {
    type: String,
    index: 1
  },
  slug: { type: String, slug: ["name"], slugPaddingSize: 0, unique: true },
other_image_ids: {
     type: Array,
}
```

When i update with 
```
Products.updateOne({_id: id}, {$set: { name: "test", other_image_ids: [{name: "imagename"}] }}, { new: true })
```

Mongo will throw error : 
```
MongoError: Updating the path 'other_image_ids.0.name' would create a conflict at 'other_image_ids'
```

**Package version**
mongoose: 5.4.0
mongodb: 3.1.10
mongoose-slug-updater: 3.0.4

**Comment by YuriGor** [comment]
Hi @vilipwong, 
take a look [here](https://github.com/YuriGor/mongoose-slug-updater/blob/master/test/bugs/update-with-set-on-array-fields.js)
If you want to update document with object as a value - try to remove `$set` operator.
This operator intended to make point changes by fully qualified string path like this:
`{ $set: { name: 'test', 'other_image_ids.0.name': 'imagename' } }`

**Comment by YuriGor** [comment]
Also note:
this behavior wasn't caused by mongoose-slug-updater,
you can try to remove plugin in your code and you will get the same issue.

**Comment by vilipwong** [comment]
I'm using this query before and works fine. I tried removing slug and no error thrown. I'll try to dig around. Thanks.

**Comment by YuriGor** [comment]
Please double check there is no error without plugin.
Look:
https://gist.github.com/YuriGor/6aaae88635c629839744dc28f6d36faf
your error reproduced without plugin.

**Comment by YuriGor** [comment]
Yes, I reproduced it finally, I'll see what's hapenning.

**Comment by YuriGor** [comment]
Just fixed this bug, thank you for reporting!
Please let me know if it works for you now.

**Comment by YuriGor** [comment]
@vilipwong dont forget to get latest 3.1.1 version
