### ISSUE TITLE
Concatenated slugs

### ISSUE THREAD

**Issue by FarazPatankar** [YuriGor/mongoose-slug-updater#9]
Hey,

I just found this library and it seems great so far. I had a quick question, would it be possible to concatenate two values to form my slug?

As an example, let's assume I am building a job board and I want the slug to be the job title followed by the company name. Could I do something like `slug: 'title', 'at', 'company.name'`.

Thanks!

**Comment by YuriGor** [comment]
Hi @FarazPatankar!
Yes, it's called [compound slug](https://github.com/YuriGor/mongoose-slug-updater/blob/master/README.md#multiple-fields-to-create-the-slug)

**Comment by FarazPatankar** [comment]
Hey @YuriGor,

Thanks for the quick response but I already tried it and it didn't work. Even in [this](https://github.com/YuriGor/mongoose-slug-updater#example-random) example, it doesn't, right?

**Comment by YuriGor** [comment]
Most of the [test](https://github.com/YuriGor/mongoose-slug-updater/tree/master/test) use compound slugs, so I expect it should work.

If something doesn't work for you there are two cases:

- you've found a bug - then report it with details on how to reproduce it.
- you've configured something wrong - then show your code, I'll try to help.

**Comment by YuriGor** [comment]
- [Schema](https://github.com/YuriGor/mongoose-slug-updater/blob/4093f42fcab6a5208dfc130c56b7ad10dd71f1ac/test/model/index.js#L45) with compound slug
- [Model](https://github.com/YuriGor/mongoose-slug-updater/blob/4093f42fcab6a5208dfc130c56b7ad10dd71f1ac/test/model/index.js#L100)
- [Usage](https://github.com/YuriGor/mongoose-slug-updater/blob/4093f42fcab6a5208dfc130c56b7ad10dd71f1ac/test/default.js#L26) example

**Comment by FarazPatankar** [comment]
I feel like I am missing something. Here's the code:
```js
const JobSchema = new Schema({
  title: {
    type: String, required: true,
  },
  slug: {
    type: String,
    slug: ['title', 'company.name'],
    uniqueSlug: true,
  },
  company: { type: Schema.Types.ObjectId, ref: 'Company' },
});
```

Shouldn't this add a slug that includes both the job title and the company name? I am only getting the job title as of now.

**Comment by YuriGor** [comment]
I've never tested Mongoose `Population` feature, but show me the rest of the code. 
Do you have some data loaded already before you are trying to update/create a document with a slug?
Ah, you also want the slug to be unique - this will definitely not work.
You may try to use `forceIdSlug: true` flag and make sure documents are loaded/filled before you are trying to generate a slug.

**Comment by FarazPatankar** [comment]
That's all the code I have actually. I am using [Forest Admin](https://www.forestadmin.com/) to add/update the data. It works fine if I use two fields from the `JobSchema` itself.

I also tried removing doing it with the `uniqueSlug` property but that didn't help either.

**Comment by YuriGor** [comment]
Well, I can't help you with it right now, refs are not supported yet.
And if I'll implement this feature(I don't promise), it will not be soon.
I expect it will be difficult to keep slug synced with fields from separate collections linked by ref.

In your case i'd recommend to have slug field in each collection, in the job and company separately.
If job slug will be unique - you still will be able to search by this slug, and company slug will be used as an url decoration only, separated by slash:
suberjob.com/my-company/my-job-wsg535
